name: Build and Release

on:
  push:
    branches:
      - dev
      - beta

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan profile detect
      
      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Giving Permission
        run: chmod +x build.sh
      
      - name: Run build script
        run: ./build.sh
      
      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: todolist-linux.zip
          path: todolist

  build-and-release-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan profile detect
      
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe integrate install
          dir
        
      - name: Install SQLiteCpp using vcpkg
        run: |
          cd vcpkg
          .\vcpkg.exe install sqlitecpp
      
      - name: Run build script
        run: .\build.bat
      
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: todolist-windows.zip
          path: D:/a/TodoList-CPP/TodoList-CPP/build/Release/todolist.exe

  create-release:
    needs: [build-and-release-linux, build-and-release-windows]
    runs-on: ubuntu-latest

    steps:

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: todolist-linux.zip
          path: todolist-linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: todolist-windows.zip
          path: todolist-windows
      
      - name: Make a zip file
        run: |
          zip -rj todolist-windows.zip todolist-windows/
          zip -rj todolist-linux.zip todolist-linux/
      

      - name: Publish Release
        uses: ncipollo/release-action@v1.14.0
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          token: ${{ secrets.PAT_TOKEN}}
          artifacts: |
            ${{ github.workspace }}/todolist-linux.zip
            ${{ github.workspace }}/todolist-windows.zip
          name: Build v${{ github.run_number }}
          tag: "v${{ github.run_number }}"      
          prerelease: true
